package site.code4fun.constant;

public enum DayOfMonth {
    FIRST_MONDAY,
    FIRST_TUESDAY,
    FIRST_WEDNESDAY,
    FIRST_THURSDAY,
    FIRST_FRIDAY,
    FIRST_SATURDAY,
    FIRST_SUNDAY,

    SECOND_MONDAY,
    SECOND_TUESDAY,
    SECOND_WEDNESDAY,
    SECOND_THURSDAY,
    SECOND_FRIDAY,
    SECOND_SATURDAY,
    SECOND_SUNDAY,

    THIRD_MONDAY,
    THIRD_TUESDAY,
    THIRD_WEDNESDAY,
    THIRD_THURSDAY,
    THIRD_FRIDAY,
    THIRD_SATURDAY,
    THIRD_SUNDAY,

    FOURTH_MONDAY,
    FOURTH_TUESDAY,
    FOURTH_WEDNESDAY,
    FOURTH_THURSDAY,
    FOURTH_FRIDAY,
    FOURTH_SATURDAY,
    FOURTH_SUNDAY,

    FIFTH_MONDAY,
    FIFTH_TUESDAY,
    FIFTH_WEDNESDAY,
    FIFTH_THURSDAY,
    FIFTH_FRIDAY,
    FIFTH_SATURDAY,
    FIFTH_SUNDAY

}
